### ISSUE TITLE
Fix checkbox sizing for longer strings

### ISSUE THREAD

**Issue by LorenzCK** [Plushtoast/TDE-Roll20-Official#223]
This issue is to track changes submitted to the character sheet as a [pull request on the Roll20 project](https://github.com/Roll20/roll20-character-sheets/pull/11446).

## Suggested changes

```css
.ui-dialog .charsheet .pad input,
.ui-dialog .charsheet .pad button,
.ui-dialog .charsheet .pad span,
.ui-dialog .charsheet .pad select,
.ui-dialog .charsheet .pad textarea {
  margin-left: 2px;
  margin-right: 2px;
  margin-bottom: 2px
}
```

```css
.ui-dialog .charsheet .row-section input[type="checkbox"],
.ui-dialog .charsheet .optionen input {
  width: 30px;
  flex-grow: 0;
}
```

[Git patch file](https://github.com/Plushtoast/TDE-Roll20-Official/files/10838690/changes.patch) attached.

## Effect

Before

![Before](https://user-images.githubusercontent.com/1782445/217109270-06ca857f-6f88-477a-a12a-f8427ccb70dd.jpg)

After

![After](https://user-images.githubusercontent.com/1782445/217109346-14d9ba59-a7dd-4b64-9ee9-a1d5de410a2c.jpg)
